Request to merge create-model into dev branch
flemton/Blogapp pull request #1
Opened 2023-07-29 16:51 UTC by flemton

In this PR, I made the below commits:

- [Created data models](https://github.com/flemton/Blogapp/commit/13f2137747882cace21ccfad35868df8e7bbd7f8)

- [Create linters.yml](https://github.com/flemton/Blogapp/commit/aa9ec55e179cb0e93b590791b26a5858c35b493f)

- [Add rubocop to local repo](https://github.com/flemton/Blogapp/commit/9fb2e71fe08ada21f257a84146e952dbe51f7d44)

- [Fix linter errors](https://github.com/flemton/Blogapp/commit/33d229c4d42ad4cbc8023b411b88691b564c2a9b)

2023-07-29 16:57 UTC, sumairq reviewed
Hi @flemton , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not use the [Microverse Readme template](https://github.com/microverseinc/readme-template).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-29 18:01 UTC, Deepakdanger requested changes
Hi <STUDENT_MENTION>, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 18:01 UTC, Deepakdanger commented on db/schema.rb
> +
- [ ] Here we have to create table for likes & comments also.
- 
```
create_table :comments do |t|
    t.text :text
    t.timestamps # this will crate uopdated_at and created_at columns
    t.references :author, foreign_key: { to_table: 'users' } # this will create author_id and a corresponding index  (but students can also add column and index in separate commands)
    t.references :post, foreign_key: true # this will create post_id and a corresponding index (but students can also add column and index in separate commands)
  end
```

```
 create_table :likes do |t|
    t.timestamps # this will crate uopdated_at and created_at columns
    t.references :author, foreign_key: { to_table: 'users' } # this will create author_id and a corresponding index  (but students can also add column and index in separate commands)
    t.references :post, foreign_key: true # this will create post_id and a corresponding index (but students can also add column and index in separate commands)
  end
```
Kindly refer 
![Screenshot from 2023-07-29 23-25-23](https://github.com/flemton/Blogapp/assets/26767383/551f1248-9982-42fc-aba5-5261798540b2)

2023-07-29 20:52 UTC, vickymarz approved these changes
Hi @flemton , 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested changes implemented✅
 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 21:00 UTC, flemton commented
Thanks Mr @vickymarz, @Deepakdanger and @sumairq for reviewing my PR, cheers.

2023-07-29 21:00 UTC, merged

2023-10-26 17:22 UTC, OyePriscilla reviewed
Hi @flemton 👏 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Implemnted model for blog app ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._